spring:
  application:
    name: findyou

  profiles:
    active: local

  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      max-file-size: 30MB      # 파일 하나당 최대 30MB
      max-request-size: 150MB   # 요청당 총 크기를 150MB로

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0
          max-tokens: 100

    retry:
      max-attempts: 2
      backoff:
        initial-interval: 2s
        multiplier: 2
        max-interval: 20s

server:
  forward-headers-strategy: framework

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

findyou:
  jwt:
    expiration-ms:
      access-token : ${JWT_ACCESS_EXPIRE_MS}
      refresh-token : ${JWT_REFRESH_EXPIRE_MS}
    secret-key : ${JWT_SECRET_KEY}

  home-stats:
    parsing-timeout-sec: ${HOME_STATS_PARSING_TIMEOUT_SEC}

  admin:
    admin-user-id: ${ADMIN_USER_ID}
    access-ttl-ms: ${ADMIN_ACCESS_TTL_MS}
    api:
      key: ${ADMIN_API_KEY}

openapi:
  protecting-animal:
    api-url: https://apis.data.go.kr/1543061/abandonmentPublicService_v2
    api-key: ${PROTECTING_ANIMAL_API_KEY}

  rescue-animal-stats:
    api-url: https://apis.data.go.kr/1543061/rescueAnimalStatsService/rescueAnimalStats
    api-key: ${PROTECTING_ANIMAL_API_KEY}

  loss-animal-info:
    api-url: https://apis.data.go.kr/1543061/lossInfoService/lossInfo
    api-key: ${PROTECTING_ANIMAL_API_KEY}

  kakao:
    api-url: "https://dapi.kakao.com/v2/local/search/address.json"
    api-key: ${KAKAO_REST_API_KEY}

  volunteer-work:
    api-url: http://openapi.1365.go.kr/openapi/service/rest/VolunteerPartcptnService/getVltrSearchWordList

cloud:
  aws:
    region:
      static: ap-northeast-2 # 서울 리전

    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}

    s3:
      bucket: ${S3_BUCKET_NAME}
      base-url: ${S3_BASE_URL}

resilience4j:
  retry:
    instances:
      kakao:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - org.springframework.web.client.RestClientException
          - org.springframework.web.client.ResourceAccessException

  ratelimiter:
    instances:
      kakao:
        limit-for-period: 7
        limit-refresh-period: 1s
        timeout-duration: 2s
